export const BRANCHES = [
  {
    id: 1,
    name: "Robinson House",
    type: "Main Branch & Laboratory",
    address: "Robinson House, CBD, Harare",
    phone: "+263 242 123456",
    hours: {
      weekdays: "8:00 AM - 5:00 PM",
      saturday: "8:00 AM - 1:00 PM",
      sunday: "Closed",
    },
    services: [
      "Full Service",
      "Main Laboratory",
      "Emergency Repairs",
      "All Tests",
    ],
    features: [
      "Same-day spectacles",
      "Free parking",
      "Wheelchair accessible",
      "Medical aid billing",
    ],
    coordinates: { lat: -17.8292, lng: 31.0522 },
    image: "/images/branches/robinson-house.png",
  },
  {
    id: 2,
    name: "Kensington",
    type: "Premium Services",
    address: "Kensington Shopping Centre, Harare",
    phone: "+263 242 234567",
    hours: {
      weekdays: "8:30 AM - 5:30 PM",
      saturday: "9:00 AM - 2:00 PM",
      sunday: "Closed",
    },
    services: [
      "Eye Tests",
      "Designer Frames",
      "Contact Lenses",
      "Children's Eye Care",
    ],
    features: [
      "Premium frames collection",
      "Child-friendly",
      "Easy parking",
      "Expert optometrists",
    ],
    coordinates: { lat: -17.81, lng: 31.04 },
    image: "/images/branches/kensington.png",
  },
  {
    id: 3,
    name: "Honeydew Lifestyle Centre",
    type: "Luxury & Designer",
    address: "Honeydew Lifestyle Centre, Greendale, Harare",
    phone: "+263 242 345678",
    hours: {
      weekdays: "9:00 AM - 6:00 PM",
      saturday: "9:00 AM - 3:00 PM",
      sunday: "10:00 AM - 1:00 PM",
    },
    services: ["Luxury Frames", "Sunglasses", "Advanced Tests", "VIP Service"],
    features: [
      "Designer brands",
      "Luxury experience",
      "Weekend hours",
      "Personal styling",
    ],
    coordinates: { lat: -17.8, lng: 31.1 },
    image: "/images/branches/honeydew.png",
  },
  {
    id: 4,
    name: "Chipinge Branch",
    type: "Community Care",
    address: "Chipinge Town Centre",
    phone: "+263 27 123456",
    hours: {
      weekdays: "8:00 AM - 4:30 PM",
      saturday: "8:00 AM - 12:00 PM",
      sunday: "Closed",
    },
    services: [
      "Full Service",
      "Rural Outreach",
      "Affordable Options",
      "Mobile Clinic",
    ],
    features: [
      "Community focused",
      "Rural outreach",
      "Affordable care",
      "Local expertise",
    ],
    coordinates: { lat: -20.2, lng: 32.62 },
    image: "/images/branches/chipinge.png",
  },
  {
    id: 5,
    name: "Chiredzi Branch",
    type: "Agricultural Community",
    address: "Chiredzi Town Centre",
    phone: "+263 31 123456",
    hours: {
      weekdays: "8:00 AM - 4:30 PM",
      saturday: "8:00 AM - 12:00 PM",
      sunday: "Closed",
    },
    services: [
      "Farm Eye Safety",
      "Dust Protection",
      "Sports Glasses",
      "Community Health",
    ],
    features: [
      "Farm safety specialists",
      "Dust-resistant options",
      "Local community",
      "Agricultural focus",
    ],
    coordinates: { lat: -21.05, lng: 31.6667 },
    image: "/images/branches/chiredzi.png",
  },
] as const;
