// constants/frames.ts - EXTRA SAFE VERSION
export const FRAMES = [
  {
    id: "1",
    name: "Giorgio Armani",
    brand: "Giorgio Armani",
    category: "designer" as const,
    priceRange: "Higher price range",
    features: ["Design", "Lightweight"],
    description: "Frames from Italy.",
    image: "/images/frames/armani.jpg",
    availableColors: ["Black", "Brown", "Gold", "Silver"],
  },
  {
    id: "2",
    name: "Police",
    brand: "Police",
    category: "designer" as const,
    priceRange: "Higher price range",
    features: ["Style", "Durable"],
    description: "Frames with contemporary style.",
    image: "/images/frames/police.jpg",
    availableColors: ["Black", "Blue", "Gunmetal", "Tortoise"],
  },
  {
    id: "3",
    name: "Gucci",
    brand: "Gucci",
    category: "designer" as const,
    priceRange: "Higher price range",
    features: ["Brand", "Design"],
    description: "Frames with design.",
    image: "/images/frames/gucci.jpg",
    availableColors: ["Black", "Gold", "Crystal", "Havana"],
  },
  {
    id: "4",
    name: "Felicia",
    brand: "Felicia",
    category: "premium" as const,
    priceRange: "Medium price range",
    features: ["Comfort", "Style"],
    description: "Frames for daily wear.",
    image: "/images/frames/felicia.jpg",
    availableColors: ["Black", "Brown", "Pink", "Clear"],
  },
  {
    id: "5",
    name: "Classic Comfort",
    brand: "Link Optical",
    category: "standard" as const,
    priceRange: "Lower price range",
    features: ["Comfort", "Durable"],
    description: "Frames for everyday use.",
    image: "/images/frames/classic.jpg",
    availableColors: ["Black", "Brown", "Grey", "Navy"],
  },
  {
    id: "6",
    name: "Basic Option",
    brand: "Link Optical",
    category: "budget" as const,
    priceRange: "Lowest price range",
    features: ["Affordable", "Durable"],
    description: "Frames at a lower price.",
    image: "/images/frames/budget.jpg",
    availableColors: ["Black", "Brown"],
  },
] as const;

export const LENSES = [
  {
    id: "l1",
    name: "Single Vision",
    type: "single" as const,
    features: ["Distance/Reading", "Protection"],
    description: "For distance or reading vision.",
    priceRange: "From $50",
  },
  {
    id: "l2",
    name: "Bifocal",
    type: "bifocal" as const,
    features: ["Distance & Reading", "For presbyopia"],
    description: "For distance and reading vision.",
    priceRange: "From $80",
  },
  {
    id: "l3",
    name: "Progressive",
    type: "progressive" as const,
    features: ["No-line multifocal", "Vision"],
    description: "Lenses for different distances.",
    priceRange: "From $120",
  },
  {
    id: "l4",
    name: "Blue Light Protection",
    type: "blue-light" as const,
    features: ["Digital protection", "Use"],
    description: "For digital device users.",
    priceRange: "From $40",
  },
] as const;

export const FRAME_CATEGORIES = [
  { id: "all", name: "All Frames", count: FRAMES.length },
  {
    id: "designer",
    name: "Designer",
    count: FRAMES.filter((f) => f.category === "designer").length,
  },
  {
    id: "premium",
    name: "Premium",
    count: FRAMES.filter((f) => f.category === "premium").length,
  },
  {
    id: "standard",
    name: "Standard",
    count: FRAMES.filter((f) => f.category === "standard").length,
  },
  {
    id: "budget",
    name: "Budget",
    count: FRAMES.filter((f) => f.category === "budget").length,
  },
] as const;
